from typing import Dict, Any

# [Keep SCOOP_KB exactly as in Code 1, with small cleanups]
SCOOP_KB: Dict[str, Any] = {
    "toppings_policy": {
        "cups": {
            "includedToppings": 0,
            "maxToppings": 2,
            "note": "Cups have no free toppings. Can add up to 2 toppings at cost.",
        },
        "sundaes": {
            "allowExtraToppings": False,
            "note": "Sundaes only get their included free toppings. No extra toppings allowed.",
        },
        "milkshakes": {
            "makeYourOwn": {
                "allowToppings": "liquid_only",
                "maxLiquidToppings": 1,
                "note": "Make Your Own Shake allows 1 liquid topping only (no dry toppings).",
            },
            "signature": {
                "allowToppings": False,
                "note": "Signature shakes do not allow toppings.",
            },
        },
        "extraToppingPriceAED": 5.0,
    },
    "flavor_policy": {
        "allowExtraFlavors": False,
        "note": "Customers can only choose flavors equal to the scoop count. No extra flavors allowed.",
    },
    "tax_policy": {
        "taxRate": 0.05,
        "taxPercentage": 5,
        "note": "5% tax is applied to the order subtotal. Example: 50 AED subtotal → 2.5 AED tax → 52.5 AED total.",
    },
    "image_defaults": {
        "square": "https://dummyimage.com/200x200/efefef/222222&text=Image",
        "rect": "https://dummyimage.com/600x400/efefef/222222&text=Image",
    },
    "displays": {
        "Ice Cream Bar": {
            "displayName": "Ice Cream Bar",
            "hint": "You’ll find your cup ice creams being scooped here.",
            "mapImage": "https://res.cloudinary.com/dslutbftw/image/upload/v1766382103/Gemini_Generated_Image_zfr9xazfr9xazfr9_bneyj3.png",
        },
        "Sundae Counter": {
            "displayName": "Sundae Counter",
            "hint": "This is where all Sundae Cups are prepared and topped.",
            "mapImage": "https://res.cloudinary.com/dslutbftw/image/upload/v1766382103/Gemini_Generated_Image_zfr9xazfr9xazfr9_bneyj3.png",
        },
        "Milkshake Bar": {
            "displayName": "Milkshake Bar",
            "hint": "Shakes are blended fresh right here.",
            "mapImage": "https://res.cloudinary.com/dslutbftw/image/upload/v1766382122/Gemini_Generated_Image_vkk0qxvkk0qxvkk0_s50m1h.png",
        },
    },
    "product_order": [
        "cup_single_kids",
        "cup_single_value",
        "cup_single_emlaaq",
        "cup_double_kids",
        "cup_double_value",
        "cup_double_emlaaq",
        "cup_triple_kids",
        "cup_triple_value",
        "sundae_single_kids",
        "sundae_single_value",
        "sundae_single_emlaaq",
        "sundae_double_kids",
        "sundae_double_value",
        "sundae_double_emlaaq",
        "sundae_triple_kids",
        "sundae_triple_value",
        "shake_chocolate_chiller_regular",
        "shake_chocolate_chiller_large",
        "shake_strawberry_mania_regular",
        "shake_strawberry_mania_large",
        "shake_jamoca_fudge_regular",
        "shake_jamoca_fudge_large",
        "shake_praline_pleasure_regular",
        "shake_praline_pleasure_large",
        "shake_make_own_regular",
    ],
    "products": {
        "cup_single_kids": {
            "id": "cup_single_kids",
            "name": "Single Scoop Cup — Kids",
            "category": "Cups",
            "size": "Kids",
            "scoops": 1,
            "priceAED": 12,
            "includedToppings": 0,
            "maxToppings": 2,
            "description": "One scoop in a kid-sized cup.",
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/wwweif79_0.jpg",
            "display": "Ice Cream Bar",
        },
        "cup_single_value": {
            "id": "cup_single_value",
            "name": "Single Scoop Cup — Value",
            "category": "Cups",
            "size": "Value",
            "scoops": 1,
            "priceAED": 16,
            "includedToppings": 0,
            "maxToppings": 2,
            "description": "One full scoop in a value-sized cup.",
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/7ysjfilv_0.jpg",
            "display": "Ice Cream Bar",
        },
        "cup_single_emlaaq": {
            "id": "cup_single_emlaaq",
            "name": "Single Scoop Cup — Emlaaq",
            "category": "Cups",
            "size": "Emlaaq",
            "scoops": 1,
            "priceAED": 20,
            "includedToppings": 0,
            "maxToppings": 2,
            "description": "One generous Emlaaq scoop.",
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/ceeoxr60_0.jpg",
            "display": "Ice Cream Bar",
        },
        "cup_double_kids": {
            "id": "cup_double_kids",
            "name": "Double Scoops Cup — Kids",
            "category": "Cups",
            "size": "Kids",
            "scoops": 2,
            "priceAED": 21,
            "includedToppings": 0,
            "maxToppings": 2,
            "description": "Two kid-sized scoops.",
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/pk1npics_0.jpg",
            "display": "Ice Cream Bar",
        },
        "cup_double_value": {
            "id": "cup_double_value",
            "name": "Double Scoops Cup — Value",
            "category": "Cups",
            "size": "Value",
            "scoops": 2,
            "priceAED": 28,
            "includedToppings": 0,
            "maxToppings": 2,
            "description": "Two value scoops — mix flavors freely.",
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/bw2cs7ou_0.jpg",
            "display": "Ice Cream Bar",
        },
        "cup_double_emlaaq": {
            "id": "cup_double_emlaaq",
            "name": "Double Scoops Cup — Emlaaq",
            "category": "Cups",
            "size": "Emlaaq",
            "scoops": 2,
            "priceAED": 37,
            "includedToppings": 0,
            "maxToppings": 2,
            "description": "Two large Emlaaq scoops.",
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/8jj0qlin_0.jpg",
            "display": "Ice Cream Bar",
        },
        "cup_triple_kids": {
            "id": "cup_triple_kids",
            "name": "Triple Scoops Cup — Kids",
            "category": "Cups",
            "size": "Kids",
            "scoops": 3,
            "priceAED": 30,
            "includedToppings": 0,
            "maxToppings": 2,
            "description": "Three kid-sized scoops.",
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/bd4a3wvg_0.jpg",
            "display": "Ice Cream Bar",
        },
        "cup_triple_value": {
            "id": "cup_triple_value",
            "name": "Triple Scoops Cup — Value",
            "category": "Cups",
            "size": "Value",
            "scoops": 3,
            "priceAED": 40,
            "includedToppings": 0,
            "maxToppings": 2,
            "description": "Three classic scoops — mix & match.",
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/i4cehyc6_0.jpg",
            "display": "Ice Cream Bar",
        },
        "sundae_single_kids": {
            "id": "sundae_single_kids",
            "name": "Single Sundae — Kids",
            "category": "Sundae Cups",
            "size": "Kids",
            "scoops": 1,
            "priceAED": 16,
            "includedToppings": 2,
            "allowExtraToppings": False,
            "description": "Kids sundae with sauces & basic toppings.",
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/qwwyrap1_0.jpg",
            "display": "Sundae Counter",
        },
        "sundae_single_value": {
            "id": "sundae_single_value",
            "name": "Single Sundae — Value",
            "category": "Sundae Cups",
            "size": "Value",
            "scoops": 1,
            "priceAED": 20,
            "includedToppings": 2,
            "allowExtraToppings": False,
            "description": "Value sundae with sauce and toppings.",
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/i36szhpa_0.jpg",
            "display": "Sundae Counter",
        },
        "sundae_single_emlaaq": {
            "id": "sundae_single_emlaaq",
            "name": "Single Sundae — Emlaaq",
            "category": "Sundae Cups",
            "size": "Emlaaq",
            "scoops": 1,
            "priceAED": 24,
            "includedToppings": 2,
            "allowExtraToppings": False,
            "description": "Emlaaq sundae with extra toppings.",
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/8d6mjr6e_0.jpg",
            "display": "Sundae Counter",
        },
        "sundae_double_kids": {
            "id": "sundae_double_kids",
            "name": "Double Sundae — Kids",
            "category": "Sundae Cups",
            "size": "Kids",
            "scoops": 2,
            "priceAED": 25,
            "includedToppings": 2,
            "allowExtraToppings": False,
            "description": "Two-scoop kids sundae.",
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/su3lvwpc_0.jpg",
            "display": "Sundae Counter",
        },
        "sundae_double_value": {
            "id": "sundae_double_value",
            "name": "Double Sundae — Value",
            "category": "Sundae Cups",
            "size": "Value",
            "scoops": 2,
            "priceAED": 31,
            "includedToppings": 2,
            "allowExtraToppings": False,
            "description": "Two-scoop value sundae.",
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/hp4r5kzc_0.jpg",
            "display": "Sundae Counter",
        },
        "sundae_double_emlaaq": {
            "id": "sundae_double_emlaaq",
            "name": "Double Sundae — Emlaaq",
            "category": "Sundae Cups",
            "size": "Emlaaq",
            "scoops": 2,
            "priceAED": 40,
            "includedToppings": 2,
            "allowExtraToppings": False,
            "description": "Two-scoop Emlaaq sundae.",
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/8d6mjr6e_0.jpg",
            "display": "Sundae Counter",
        },
        "sundae_triple_kids": {
            "id": "sundae_triple_kids",
            "name": "Triple Sundae — Kids",
            "category": "Sundae Cups",
            "size": "Kids",
            "scoops": 3,
            "priceAED": 36,
            "includedToppings": 2,
            "allowExtraToppings": False,
            "description": "Three-scoop kids sundae.",
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/l64p228m_0.jpg",
            "display": "Sundae Counter",
        },
        "sundae_triple_value": {
            "id": "sundae_triple_value",
            "name": "Triple Sundae — Value",
            "category": "Sundae Cups",
            "size": "Value",
            "scoops": 3,
            "priceAED": 44,
            "includedToppings": 2,
            "allowExtraToppings": False,
            "description": "Three-scoop value sundae.",
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/l64p228m_0.jpg",
            "display": "Sundae Counter",
        },
        "shake_chocolate_chiller_regular": {
            "id": "shake_chocolate_chiller_regular",
            "name": "Chocolate Chiller Thick Shake - Regular",
            "category": "Milk Shakes",
            "size": "Regular",
            "priceAED": 27,
            "description": "Chocolate mousse royale ice cream with vanilla ice cream..",
            "allowFlavorSelection": False,
            "allowToppings": False,
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/nhk3ekf4_0.jpg",
            "display": "Milkshake Bar",
        },
        "shake_chocolate_chiller_large": {
            "id": "shake_chocolate_chiller_large",
            "name": "Chocolate Chiller Thick Shake - Large",
            "category": "Milk Shakes",
            "size": "Large",
            "priceAED": 32,
            "description": "Chocolate mousse royale ice cream with vanilla ice cream.",
            "allowFlavorSelection": False,
            "allowToppings": False,
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/igdoeihc_0.jpg",
            "display": "Milkshake Bar",
        },
        "shake_strawberry_mania_regular": {
            "id": "shake_strawberry_mania_regular",
            "name": "Strawberry Mania Thick Shake - Regular",
            "category": "Milk Shakes",
            "size": "Regular",
            "priceAED": 27,
            "description": "Vanilla and very berry strawberry ice cream with banana pieces.",
            "allowFlavorSelection": False,
            "allowToppings": False,
            "additionalNote": "no banana",
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/i1yr0rqp_0.jpg",
            "display": "Milkshake Bar",
        },
        "shake_strawberry_mania_large": {
            "id": "shake_strawberry_mania_large",
            "name": "Strawberry Mania Thick Shake - Large",
            "category": "Milk Shakes",
            "size": "Large",
            "priceAED": 30,
            "description": "Vanilla and very berry strawberry ice cream with banana pieces.",
            "allowFlavorSelection": False,
            "allowToppings": False,
            "additionalNote": "no banana",
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/aggee5ui_0.jpg",
            "display": "Milkshake Bar",
        },
        "shake_jamoca_fudge_regular": {
            "id": "shake_jamoca_fudge_regular",
            "name": "Jamoca Fudge Thick Shake - Regular",
            "category": "Milk Shakes",
            "size": "Regular",
            "priceAED": 27,
            "description": "Jamoca almond fudge ice cream.",
            "allowFlavorSelection": False,
            "allowToppings": False,
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/h3cmi7b7_0.jpg",
            "display": "Milkshake Bar",
        },
        "shake_jamoca_fudge_large": {
            "id": "shake_jamoca_fudge_large",
            "name": "Jamoca Fudge Thick Shake - Large",
            "category": "Milk Shakes",
            "size": "Large",
            "priceAED": 32,
            "description": "Jamoca almond fudge ice cream.",
            "allowFlavorSelection": False,
            "allowToppings": False,
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/9i34ocls_0.jpg",
            "display": "Milkshake Bar",
        },
        "shake_praline_pleasure_regular": {
            "id": "shake_praline_pleasure_regular",
            "name": "Praline Pleasure Thick Shake - Regular",
            "category": "Milk Shakes",
            "size": "Regular",
            "priceAED": 27,
            "description": "Pralines in cream ice cream with Jamoca almond fudge ice cream.",
            "allowFlavorSelection": False,
            "allowToppings": False,
            "additionalNote": "extra spoon",
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/luqwa7y8_0.jpg",
            "display": "Milkshake Bar",
        },
        "shake_praline_pleasure_large": {
            "id": "shake_praline_pleasure_large",
            "name": "Praline Pleasure Thick Shake - Large",
            "category": "Milk Shakes",
            "size": "Large",
            "priceAED": 32,
            "description": "Pralines in cream ice cream with Jamoca almond fudge ice cream.",
            "allowFlavorSelection": False,
            "allowToppings": False,
            "additionalNote": "extra spoon",
            "imageUrl": "https://f.nooncdn.com/food_production/food/menu/M8654550136017771626691016A/5n85jghc_0.jpg",
            "display": "Milkshake Bar",
        },
        "shake_make_own_regular": {
            "id": "shake_make_own_regular",
            "name": "Make Your Own Thick Shake - Regular (3 Scoops)",
            "category": "Milk Shakes",
            "size": "Regular",
            "scoops": 3,
            "priceAED": 25,
            "description": "Choose 3 flavors, 2.5 oz per scoop. Allows 1 liquid topping.",
            "allowFlavorSelection": True,
            "allowToppings": "liquid_only",
            "maxLiquidToppings": 1,
            "additionalNote": "extra straw",
            "allowedFlavorNames": [
                "Chocolate",
                "Chocolate Chip",
                "Chocolate Mousse Royale",
                "World Class Chocolate",
                "Strawberry Cheesecake",
                "Very Berry Strawberry",
                "Blue Berry Crumble",
                "Cookies N Cream",
                "Gold Medal Ribbon",
                "Jamoca Almond Fudge",
                "Mint Chocolate Chip",
                "Pralines N Cream",
                "Vanilla",
                "Love Potion 31",
                "Rainbow Sherbet",
                "Nsa Caramel Turtle",
                "Mango Sticky Rice",
                "German Chocolate Cake",
                "Cotton Candy",
                "Maui Brownie Madness",
                "Base Ball Nut",
                "Citrus Twist",
                "Pistachio Almond",
                "Peanut Butter N Chocolate",
                "Chocolate Chip Cookie Dough",
            ],
            "imageUrl": "https://dummyimage.com/200x200/efefef/222222&text=Make+Your+Own+Shake",
            "display": "Milkshake Bar",
        },
    },
    "flavors": [
        {
            "id": "flv_chocolate",
            "name": "Chocolate",
            "classification": "choco",
            "imageUrl": "https://www.baskinrobbinsmea.com/wp-content/uploads/2020/05/Chocolate.jpg",
            "available": True,
        },
        {
            "id": "flv_chocolate_chip",
            "name": "Chocolate Chip",
            "classification": "choco",
            "imageUrl": "https://www.baskinrobbinsmea.com/wp-content/uploads/2020/05/Chocolate-Chip.jpg",
            "available": True,
        },
        {
            "id": "flv_chocolate_mousse_royale",
            "name": "Chocolate Mousse Royale",
            "classification": "choco",
            "imageUrl": "https://www.baskinrobbinsmea.com/wp-content/uploads/2020/05/Chocolate-Mousse-Royale.jpg",
            "available": True,
        },
        {
            "id": "flv_world_class_chocolate",
            "name": "World Class Chocolate",
            "classification": "choco",
            "imageUrl": "https://www.baskinrobbinsmea.com/wp-content/uploads/2020/05/World-Class-Chocolate.jpg",
            "available": True,
        },
        {
            "id": "flv_strawberry_cheesecake",
            "name": "Strawberry Cheesecake",
            "classification": "berry",
            "imageUrl": "https://www.baskinrobbinsmea.com/wp-content/uploads/2020/05/Strawberry-Cheese-Cake.jpg",
            "available": True,
        },
        {
            "id": "flv_very_berry_strawberry",
            "name": "Very Berry Strawberry",
            "classification": "berry",
            "imageUrl": "https://www.baskinrobbinsmea.com/wp-content/uploads/2020/05/verY-berry-strawberry.jpg",
            "available": True,
        },
        {
            "id": "flv_blue_berry_crumble",
            "name": "Blue Berry Crumble",
            "classification": "berry",
            "imageUrl": "https://res.cloudinary.com/dslutbftw/image/upload/v1763288485/Screenshot_2025-11-16_154743_yccg7x.png",
            "available": True,
        },
        {
            "id": "flv_cookies_n_cream",
            "name": "Cookies N Cream",
            "classification": "others",
            "imageUrl": "https://www.baskinrobbinsmea.com/wp-content/uploads/2020/05/Cookies-N-Cream.jpg",
            "available": True,
        },
        {
            "id": "flv_gold_medal_ribbon",
            "name": "Gold Medal Ribbon",
            "classification": "others",
            "imageUrl": "https://www.baskinrobbinsmea.com/wp-content/uploads/2020/05/Gold-Medal-Ribbon.jpg",
            "available": True,
        },
        {
            "id": "flv_jamoca_almond_fudge",
            "name": "Jamoca Almond Fudge",
            "classification": "others",
            "imageUrl": "https://www.baskinrobbinsmea.com/wp-content/uploads/2020/05/Jamoca-Almond-Fudge.jpg",
            "available": True,
        },
        {
            "id": "flv_mint_chocolate_chip",
            "name": "Mint Chocolate Chip",
            "classification": "others",
            "imageUrl": "https://www.baskinrobbinsmea.com/wp-content/uploads/2020/05/Mint-Chocolate-Chip.jpg",
            "available": True,
        },
        {
            "id": "flv_pralines_n_cream",
            "name": "Pralines N Cream",
            "classification": "others",
            "imageUrl": "https://www.baskinrobbinsmea.com/wp-content/uploads/2020/05/Pralines-N-Cream.jpg",
            "available": True,
        },
        {
            "id": "flv_vanilla",
            "name": "Vanilla",
            "classification": "others",
            "imageUrl": "https://www.baskinrobbinsmea.com/wp-content/uploads/2020/05/Vanilla.jpg",
            "available": True,
        },
        {
            "id": "flv_love_potion_31",
            "name": "Love Potion 31",
            "classification": "others",
            "imageUrl": "https://www.baskinrobbinsmea.com/wp-content/uploads/2020/05/Love-Portion-31.jpg",
            "available": True,
        },
        {
            "id": "flv_rainbow_sherbet",
            "name": "Rainbow Sherbet",
            "classification": "others",
            "imageUrl": "https://www.baskinrobbinsmea.com/wp-content/uploads/2020/05/Rainbow-Sherbet.jpg",
            "available": True,
        },
        {
            "id": "flv_nsa_caramel_turtle",
            "name": "Nsa Caramel Turtle",
            "classification": "others",
            "imageUrl": "https://www.baskinrobbinsmea.com/wp-content/uploads/2020/05/NSA-Caramel-Turtle.jpg",
            "available": True,
        },
        {
            "id": "flv_mango_sticky_rice",
            "name": "Mango Sticky Rice",
            "classification": "others",
            "imageUrl": "https://www.baskinrobbinsmea.com/wp-content/uploads/2020/06/It-takes-two-to-mango.jpg",
            "available": True,
        },
        {
            "id": "flv_german_chocolate_cake",
            "name": "German Chocolate Cake",
            "classification": "others",
            "imageUrl": "https://cdn.trendhunterstatic.com/thumbs/546/german-chocolate-cake-ice-cream.jpeg",
            "available": True,
        },
        {
            "id": "flv_cotton_candy",
            "name": "Cotton Candy",
            "classification": "others",
            "imageUrl": "https://www.baskinrobbinsmea.com/wp-content/uploads/2020/05/Cotton-Candy.jpg",
            "available": True,
        },
        {
            "id": "flv_cup_of_cocoa_tub",
            "name": "Cup of cocoa Tub",
            "classification": "choco",
            "imageUrl": "https://www.baskinrobbinsmea.com/wp-content/uploads/2020/05/Chocolate.jpg",
            "available": True,
        },
    ],
    "toppings": [
        # --- Liquid Toppings ---
        {
            "id": "top_hot_butterscotch",
            "name": "Hot Butterscotch",
            "type": "liquid",
            "priceAED": 5,
            "imageUrl": "https://thecafesucrefarine.com/wp-content/uploads/Ridiculously-Easy-Butterscotch-Sauce-1.jpg",
        },
        {
            "id": "top_hot_fudge",
            "name": "Hot Fudge",
            "type": "liquid",
            "priceAED": 5,
            "imageUrl": "https://images.squarespace-cdn.com/content/v1/58e2595c3e00be0ae51453aa/1725237286880-PCLY565558ZWKOM6OUHZ/hot+fudge-12.jpg",
        },
        {
            "id": "top_strawberry",
            "name": "Strawberry",
            "type": "liquid",
            "priceAED": 5,
            "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/7/79/Icecream_with_strawberry_sauce.jpg",
        },
        {
            "id": "top_chocolate_syrup",
            "name": "Chocolate Syrup",
            "type": "liquid",
            "priceAED": 5,
            "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Chocolate_syrup_topping_on_ice_cream.JPG",
        },
        {
            "id": "top_nutella",
            "name": "Nutella",
            "type": "liquid",
            "priceAED": 6,
            "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/9/9b/Nutella_ak.jpg",
        },
        {
            "id": "top_pistachio_liquid",
            "name": "Pistachio Liquid Topping Serve 1",
            "type": "liquid",
            "priceAED": 6,
            "imageUrl": "https://www.loveandoliveoil.com/wp-content/uploads/2025/04/homemade-pistachio-syrup-1.jpg",
        },
        # --- Dry Toppings ---
        {
            "id": "top_almonds_diced",
            "name": "Almonds Diced",
            "type": "dry",
            "priceAED": 5,
            "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/a/af/Bowl_of_chopped_almonds_no_bg.png",
        },
        {
            "id": "top_mms",
            "name": "M&M's",
            "type": "dry",
            "priceAED": 5,
            "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/e/e5/Plain-M%26Ms-Pile.jpg",
        },
        {
            "id": "top_kitkat_crush",
            "name": "Kitkat Crush",
            "type": "dry",
            "priceAED": 5,
            "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/f/fc/Kit-Kat-Split.jpg",
        },
        {
            "id": "top_rainbow_sprinkles",
            "name": "Rainbow Sprinkles",
            "type": "dry",
            "priceAED": 5,
            "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/e/e2/Colored_sprinkles.jpg",
        },
        {
            "id": "top_chocolate_sprinkles",
            "name": "Chocolate Sprinkles",
            "type": "dry",
            "priceAED": 5,
            "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/3/37/Hagelslag_chocolate_sprinkles.jpg",
        },
        {
            "id": "top_pink_white_marshmallow",
            "name": "Pink & White Marshmallow",
            "type": "dry",
            "priceAED": 5,
            "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/c/ca/Pink_Marshmallows.jpg",
        },
        {
            "id": "top_maltesers",
            "name": "Maltesers",
            "type": "dry",
            "priceAED": 6,
            "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/48/Maltesers-Pile-and-Split.jpg",
        },
        {
            "id": "top_mms_peanut",
            "name": "M&M's Peanut",
            "type": "dry",
            "priceAED": 6,
            "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/a/aa/M%26m1.jpg",
        },
        {
            "id": "top_skittles",
            "name": "Skittles",
            "type": "dry",
            "priceAED": 6,
            "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/8/81/Skittles-Candies-Pile.jpg",
        },
        {
            "id": "top_haribo_gold_bears",
            "name": "Haribo Gold Bears Serve 1",
            "type": "dry",
            "priceAED": 6,
            "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/b/bd/Haribo_gb.jpg",
        },
        {
            "id": "top_haribo_raspberry_blackberry",
            "name": "Haribo Raspberry & Blackberry Serve 1",
            "type": "dry",
            "priceAED": 6,
            "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/6/6a/Haribo_Gelee-Himbeeren_und_-Brombeeren-5468.jpg",
        },
        {
            "id": "top_pistachio_diced_roasted",
            "name": "Pistachio Diced Roasted Serve 1",
            "type": "dry",
            "priceAED": 6,
            "imageUrl": "https://upload.wikimedia.org/wikipedia/commons/4/4b/K%C3%BCnefe_-_pistachio.jpg",
        },
    ],
}

# Normalize product prices
for _p in SCOOP_KB.get("products", {}).values():
    try:
        _p["priceAED"] = (
            round(float(_p.get("priceAED") or 0.0), 2)
            if _p.get("priceAED") is not None
            else None
        )
    except (TypeError, ValueError):
        _p["priceAED"] = None
